@startuml Diagrama
class SuperMario
{
-MenuPrincipal [1]
-Niveles [*]
-Jugador [1]
-PuntajeTotal
}

class Nivel
{
-Escenario [1]
-Enemigos [*]
-PowerUps [*]
-Cronometro [1]
-PuntajeNivel
}

class Jugador
{
-PersonajeJugable [1]
-PuntajeJugador
-Vidas
}

class PersonajeJugable
{
+Caminar(Jugador)
+Saltar(Jugador)
+Atacar(Jugador)
}

class Enemigo
{
-Vida (100)
-Posicion
+Atacar(PersonajeJugable)
+Morir(PersonajeJugable)
}

class PowerUp
{
-Duracion(10)
+Aplicar(PersonajeJugable)
}

class Objeto
class Escenario
{
-Bloques [*]
-Tuberias [*]
-Bandera [1]
-Castillo [1]
}
class Personaje
class Cronometro
class Musica
class Puntaje
class Bloques
class Tuberias
class Bandera
class Castillo
class Movimiento
class Menu
class FlorFuego
class Hongo
class Estrella
class ChampiñonVida
class Caparazon
class Moneda
class Koopa
class Bowser
class BalaBill
class Boo
class Planta
class Peach
class Gomba

SuperMario "1"*--"*" Nivel
SuperMario *-- Jugador
SuperMario *-- Personaje
Personaje <|-- PersonajeJugable
Personaje <|-- Peach
Enemigo <|-- Koopa
Enemigo <|-- Bowser
Enemigo <|-- BalaBill
Enemigo <|-- Planta
Enemigo <|-- Boo
Enemigo <|-- Gomba
Jugador o-- PersonajeJugable
PersonajeJugable o-- PowerUp
Nivel "1"*--"*" Enemigo
Nivel "1"*--"*" Objeto
Nivel *-- Escenario
Nivel *-- Puntaje
Nivel *-- Musica
Nivel *-- Cronometro
Nivel "1"*-- "*" PowerUp
Objeto "1"<|--"*" Moneda
Objeto <|-- Caparazon
Objeto <|-- ChampiñonVida
PowerUp <|-- Estrella
PowerUp <|-- Hongo
PowerUp <|-- FlorFuego
Escenario *-- Bloques
Escenario *-- Tuberias
Escenario *-- Bandera
Escenario *-- Castillo
PersonajeJugable *-- Movimiento
SuperMario *-- Menu
@enduml
